/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje3;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erayk
 */
public class MusteriEkran extends javax.swing.JFrame {
         DefaultTableModel model;
         DefaultTableModel model3;
         
         Database_Connect baglan=new Database_Connect();
         
    /**
     * Creates new form MusteriEkran
     */
    public MusteriEkran() {
        initComponents();
        model= (DefaultTableModel) Musteri_Tablo.getModel();
        model3= (DefaultTableModel) MusteriEkranHesap_Tablo.getModel();
        
       // Musteri_Veri_Gor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Musteri_Tablo = new javax.swing.JTable();
        MusteriEkranVeriGuncelle_b = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Musteri_Ekran_Guncelle_AdSoyad = new javax.swing.JTextField();
        Musteri_Ekran_Guncelle_Email = new javax.swing.JTextField();
        Musteri_Ekran_Guncelle_Tel = new javax.swing.JTextField();
        Musteri_Ekran_Guncelle_Adres = new javax.swing.JTextField();
        Musteri_Ekran_Guncelle_Sifre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        MusteriEkranHesap_Tablo = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        Musteri_Ekran_Miktar_Gir = new javax.swing.JTextField();
        Musteri_Ekran_Para_Yatır_b = new javax.swing.JButton();
        Musteri_Ekran_Para_Cek_b = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        Musteri_Tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CID", "PASSWORD", "NAMESURNAME", "TCNO", "EMAIL", "CREATEDDATE", "TELNR", "USERID", "ADRESS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Musteri_Tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Musteri_TabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Musteri_Tablo);
        if (Musteri_Tablo.getColumnModel().getColumnCount() > 0) {
            Musteri_Tablo.getColumnModel().getColumn(0).setResizable(false);
            Musteri_Tablo.getColumnModel().getColumn(1).setResizable(false);
            Musteri_Tablo.getColumnModel().getColumn(2).setResizable(false);
            Musteri_Tablo.getColumnModel().getColumn(3).setResizable(false);
            Musteri_Tablo.getColumnModel().getColumn(4).setResizable(false);
            Musteri_Tablo.getColumnModel().getColumn(5).setResizable(false);
            Musteri_Tablo.getColumnModel().getColumn(6).setResizable(false);
            Musteri_Tablo.getColumnModel().getColumn(7).setResizable(false);
            Musteri_Tablo.getColumnModel().getColumn(8).setResizable(false);
        }

        MusteriEkranVeriGuncelle_b.setBackground(new java.awt.Color(51, 0, 255));
        MusteriEkranVeriGuncelle_b.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MusteriEkranVeriGuncelle_b.setText("Verileri Güncelle");
        MusteriEkranVeriGuncelle_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriEkranVeriGuncelle_bActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ad-Soyad :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Şifre :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Email :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Telefon No :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Adres :");

        MusteriEkranHesap_Tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AID", "BALANCE", "CID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MusteriEkranHesap_Tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MusteriEkranHesap_TabloMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MusteriEkranHesap_Tablo);
        if (MusteriEkranHesap_Tablo.getColumnModel().getColumnCount() > 0) {
            MusteriEkranHesap_Tablo.getColumnModel().getColumn(0).setResizable(false);
            MusteriEkranHesap_Tablo.getColumnModel().getColumn(1).setResizable(false);
            MusteriEkranHesap_Tablo.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Miktar Giriniz   :");

        Musteri_Ekran_Para_Yatır_b.setBackground(new java.awt.Color(51, 0, 255));
        Musteri_Ekran_Para_Yatır_b.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Musteri_Ekran_Para_Yatır_b.setText("Para Yatır");
        Musteri_Ekran_Para_Yatır_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Musteri_Ekran_Para_Yatır_bActionPerformed(evt);
            }
        });

        Musteri_Ekran_Para_Cek_b.setBackground(new java.awt.Color(51, 0, 255));
        Musteri_Ekran_Para_Cek_b.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Musteri_Ekran_Para_Cek_b.setText("Para Çek");
        Musteri_Ekran_Para_Cek_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Musteri_Ekran_Para_Cek_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(93, 93, 93)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(60, 60, 60)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(86, 86, 86)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Musteri_Ekran_Guncelle_Tel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Musteri_Ekran_Guncelle_Sifre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                        .addComponent(Musteri_Ekran_Guncelle_AdSoyad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                        .addComponent(Musteri_Ekran_Guncelle_Email, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(Musteri_Ekran_Guncelle_Adres, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MusteriEkranVeriGuncelle_b))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Musteri_Ekran_Para_Yatır_b, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(Musteri_Ekran_Para_Cek_b, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(26, 26, 26)
                                        .addComponent(Musteri_Ekran_Miktar_Gir, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel5)))
                        .addGap(307, 307, 307))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Musteri_Ekran_Guncelle_Sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Musteri_Ekran_Guncelle_AdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Musteri_Ekran_Guncelle_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Musteri_Ekran_Guncelle_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Musteri_Ekran_Guncelle_Adres))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Musteri_Ekran_Miktar_Gir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 53, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MusteriEkranVeriGuncelle_b, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Musteri_Ekran_Para_Cek_b, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Musteri_Ekran_Para_Yatır_b, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Musteri_TabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Musteri_TabloMouseClicked
        // TODO add your handling code here:
        
      Musteri_Ekran_Guncelle_Sifre.setText((String) model.getValueAt(Musteri_Tablo.getSelectedRow(),1));// 2.sütun
      Musteri_Ekran_Guncelle_AdSoyad.setText((String) model.getValueAt(Musteri_Tablo.getSelectedRow(),2));// 3.sütun
      Musteri_Ekran_Guncelle_Email.setText((String) model.getValueAt(Musteri_Tablo.getSelectedRow(),4)); //5.sütun
      Musteri_Ekran_Guncelle_Tel.setText((String) model.getValueAt(Musteri_Tablo.getSelectedRow(),6)); // 7.sütun
      Musteri_Ekran_Guncelle_Adres.setText((String) model.getValueAt(Musteri_Tablo.getSelectedRow(),8)); //9.sütun
      
    }//GEN-LAST:event_Musteri_TabloMouseClicked

    private void MusteriEkranVeriGuncelle_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriEkranVeriGuncelle_bActionPerformed
        // TODO add your handling code here:
        
      String yedeksifre=Musteri_Ekran_Guncelle_Sifre.getText();
      String yedekadsoyad=Musteri_Ekran_Guncelle_AdSoyad.getText();
      String yedekemail=Musteri_Ekran_Guncelle_Email.getText();
      String yedektel=Musteri_Ekran_Guncelle_Tel.getText();
      String yedekadres=Musteri_Ekran_Guncelle_Adres.getText();
      
      if(Musteri_Tablo.getSelectedRow()==-1){
          
      if(model.getRowCount()!=0){ // Güncellenecek satır seçili değil
          
          JOptionPane.showMessageDialog(null,"Lütfen güncellenecek satırı seçiniz"); 
      }    
          
      }
      else{
          
       int yedekcid=(int) model.getValueAt(Musteri_Tablo.getSelectedRow(),0);// 0.sütundaki customerid yi çeker
       
       baglan.Musteri_Veri_Guncelle(yedekcid,yedeksifre,yedekadsoyad,yedekemail,yedektel,yedekadres);
      
         
         String x = String.valueOf(model.getValueAt(Musteri_Tablo.getSelectedRow(),0)); // Obje String dönüştürme
     
       Musteri_Veri_Gor(x);
       
       JOptionPane.showMessageDialog(null,"Güncelleme yapıldı"); 
       
      }
      
    }//GEN-LAST:event_MusteriEkranVeriGuncelle_bActionPerformed

    private void MusteriEkranHesap_TabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusteriEkranHesap_TabloMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_MusteriEkranHesap_TabloMouseClicked

    private void Musteri_Ekran_Para_Yatır_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Musteri_Ekran_Para_Yatır_bActionPerformed
        // TODO add your handling code here:
          
        
        
        
    }//GEN-LAST:event_Musteri_Ekran_Para_Yatır_bActionPerformed

    private void Musteri_Ekran_Para_Cek_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Musteri_Ekran_Para_Cek_bActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_Musteri_Ekran_Para_Cek_bActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void Musteri_Veri_Gor(String ad){
        
        model.setRowCount(0); // Musterileri gosteren tablo her seferınde sıfırlanır
        ArrayList<Musteri> musteri_veri=new ArrayList<Musteri>();
        
        musteri_veri=baglan.Musteri_Veri_Getir(ad);
        
        if(musteri_veri != null){
            
         for(Musteri musteri: musteri_veri){
             
         Object[] add_data={musteri.getCID(),musteri.getPASSWORD(),musteri.getNAMESURNAME(),musteri.getTCNO(),
             
                    musteri.getEMAIL(),musteri.getCREATEDDATE(),musteri.getTELNR(),
                    musteri.getUSERID(),musteri.getADRESS()};    
             
            model.addRow(add_data); // tabloya veriler eklendi
         }   
            
        }
    }
     public void Musteri_Hesap_Gor(String ad){
        
        model3.setRowCount(0); // Musterileri gosteren tablo her seferınde sıfırlanır
        ArrayList<Hesap> hesap_veri=new ArrayList<Hesap>();
        
        hesap_veri=baglan.Musteri_Hesap_Getir(ad);
        
        if(hesap_veri != null){
            
         for(Hesap hesap: hesap_veri){
             
         Object[] add_data={hesap.getAID(),hesap.getBALANCE(),hesap.getCID() };    
             
            model3.addRow(add_data); // tabloya veriler eklendi
         }   
            
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MusteriEkranHesap_Tablo;
    private javax.swing.JButton MusteriEkranVeriGuncelle_b;
    private javax.swing.JTextField Musteri_Ekran_Guncelle_AdSoyad;
    private javax.swing.JTextField Musteri_Ekran_Guncelle_Adres;
    private javax.swing.JTextField Musteri_Ekran_Guncelle_Email;
    private javax.swing.JTextField Musteri_Ekran_Guncelle_Sifre;
    private javax.swing.JTextField Musteri_Ekran_Guncelle_Tel;
    private javax.swing.JTextField Musteri_Ekran_Miktar_Gir;
    private javax.swing.JButton Musteri_Ekran_Para_Cek_b;
    private javax.swing.JButton Musteri_Ekran_Para_Yatır_b;
    private javax.swing.JTable Musteri_Tablo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
